name: Tests

on:
  push:
    branches: [main, ci-test-*]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
      with:
        repository: TeamRobotmad/badge-2024-software
    - name: Manage submodule
      run: |
        git submodule update --init
        cd ./sim/apps/BadgeBot
        git checkout  ${{ github.head_ref || github.ref_name }} 
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./sim/requirements.txt
        pip install pytest
    - name: Run the tests
      run: |
        cd ./sim/apps/BadgeBot
        pytest tests
